name: storify
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  firebase_storage: ^2.1.0+1
  firebase_auth: ^0.8.3
  google_sign_in: ^4.0.1+1
  cloud_firestore: ^0.9.7+2
  provider: ^3.1.0
  flutter_facebook_login: ^3.0.0
  timeago: 2.0.17 #"last seen 5 minutes ago" example


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/google_signin_button.png
    - assets/images/continue_with_facebook.png
    - assets/logo.png


  uses-material-design: true



