name: storify
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  firebase_storage: ^7.0.0
  firebase_auth: ^0.20.1
  google_sign_in: ^4.0.1+1
  cloud_firestore: ^0.16.0+1
  firebase_core: ^0.7.0
  provider: ^5.0.0
  flutter_facebook_login: ^3.0.0
  timeago: 2.0.17 #"last seen 5 minutes ago" example
  flutter_signin_button: ^2.0.0
  ionicons: ^0.1.2
  cached_network_image: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/google_signin_button.png
    - assets/images/continue_with_facebook.png
    - assets/logo.png
    - assets/land1.jpg
    - assets/landing2.jpg
    - assets/test11.png

  fonts:
  - family: Pacifico
    fonts:
      - asset: fonts/Pacifico-Regular.ttf

  uses-material-design: true



